version: dev.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
platform:
- x64
- Win32
configuration:
- Release
- Debug
shallow_clone: true
clone_depth: 5
build:
  project: Dn-FamiTracker.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    call release.bat %configuration% %platform% %APPVEYOR_BUILD_VERSION%
artifacts:
- path: distribute\*.7z
  name: 7z
deploy: off