version: dev.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
platform:
- x64
- Win32
configuration:
- Release
- Debug
shallow_clone: true
clone_depth: 5
build:
  project: Dn-FamiTracker.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    cd %platform%\%configuration%

    move *.exe Dn-%APPVEYOR_BUILD_VERSION%-%platform%-%configuration%.exe
artifacts:
- path: $(platform)\$(configuration)\*.exe
  name: exe
- path: $(platform)\$(configuration)\*.pdb
  name: pdb
- path: $(platform)\$(configuration)\*.chm
  name: chm
deploy: off